[build]
rustflags = ["-Zlocation-detail=none"]        # custom flags to pass to all compiler invocations
target = "x86_64-unknown-linux-gnu"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
